### ISSUE TITLE
Compatibility with IE11 ? XPathResult is undefined

### ISSUE THREAD

**Issue by Gorbus** [catamphetamine/read-excel-file#26]
Hello,

Thanks for the great package. However its seems it is not working with IE as Xpath is not recognized in it. I get the following error :

description"'XPathResult' is undefined"

 Any idea how to solve this ? thanks a bunch in advance.

**Comment by catamphetamine** [comment]
Seems that XPath is not supported in IE11:
https://developer.mozilla.org/en-US/docs/Web/API/Document/evaluate#Browser_compatibility

The code currently uses `new DOMParser().evaluate()` but it's unavailable in IE11.
They say there was some `new DOMParser().selectSingleNode()` method in IE10 which worked similarly to `.evaluate()`.
https://stackoverflow.com/questions/19300859/how-do-you-run-an-xpath-query-in-ie11

There's also `wicked-good-xpath` library which is a polyfill for `new DOMParser.evaluate()`.
https://github.com/google/wicked-good-xpath
It's written in Google Closure and the size is about 25 kilobytes.
The latest release was somewhere in 2016.

The Node.js version of this library uses `xpath` library which implements XPath in javascript.
The browser version now also uses that `xpath` library instead of native `DOMParser`.
This resulted in the browser bundle becoming larger in size by 100 kilobytes.
The demo now works in IE11.

**Comment by radet-hong** [comment]
Error: Sheet #1 data is missing from the *.xlsx file.
    at readXlsx.js:501
    at e.default (readXlsx.js:90)
    at e.default (readXlsxFileContents.js:22)
    at readXlsxFileBrowser.js:42
Please help me to resolve this error.

**Comment by catamphetamine** [comment]
This means that there's no `xl/worksheets/sheet1.xml` file inside the Excel file.

Unzip the `*.xlsx` file.
Open `xl/workbook.xml`.
Find `<sheets>` list there and see the available `sheetId`s. See that `sheetId=1` is the first one.
Open `xl/worksheets` directory.
See that there's no `xl/worksheets/sheet1.xml` file there.
I guess that could mean that the `*.xlsx` file is incorrect.

**Comment by catamphetamine** [comment]
Seems to be the same issue: https://github.com/tidyverse/readxl/issues/80

**Comment by catamphetamine** [comment]
Seems that the correct way of mapping sheets to file names is by reading the `xl/_rels/workbook.xml.rels`.
https://github.com/tidyverse/readxl/issues/104
@radet-hong Provide your Excel file for testing.

**Comment by catamphetamine** [comment]
@radet-hong Released version `4.x` with the fix.

**Comment by radet-hong** [comment]
> @radet-hong Released version `4.x` with the fix.

Thank you for your support. Now it work.
